# Design 
version: 1.0
blueprint:
  imports: "../**/*"
  name: "LoginLogout"
  params:
    - "url"
    - "username"
    - "password"
  simulation:
    config:
      autoWait: 10
      autoScreenshots: true
      actionPrefix: "LL_"
      browser: 
        name: "chrome"
        version: 56
    actions:
      - name: "HitServer"
        commands:
          - hit: "{{url}}"
      - name: "Login"
        commands:
          - sendKeys:
              selector: "#ctl00_Content_Login1_UserName"
              text: "{{username}}"
          - sendKeys:
              selector: "#ctl00_Content_Login1_Password"
              text: "{{password}}"
          - click: "#ctl00_Content_Login1_LoginButton"
      - name: "Logout"
        commands:
          - click: "#unified-nav-header-user-account-menu-button"
          - click: "#ukg-menu-hdr_logout"
  script:
    assertions:
      - name: "Find 'UKG Pro' on landing page"
        text: "UKG Pro"
    files:
      - path: "Users.dat"
        variants: 
          - "Calendar_Users.dat"
          - "GSDB_Users.dat"
          - "ServiceB_Users.dat"
    parameters: 
      - name: "Username"
        replace: "{{username}}"
        file: "Users"
      - name: "Password"
        replace: "{{password}}"
        file: "Users"
    correlations:
      - name: "C_XSRF_TOKEN"
        boundary:
          left: "XSRF_TOKEN="
          right: "\n"
        search: "headers"
      - import: "xsrf-token.correlation.yml"
    logic:
      - type: "loop"
        loop:
          iterations: 5
          method: "GET"
          url: "*/report/*/status"
          action: "Get Report Status"
          excludeUrl: "*/report/{{ReportID}}_2/status"