version: 1
blueprint:
  name: "View Pay"
  params: 
    - "url"
    - "username"
    - "password"
  simulation:
    config:
      actionWait: 5
      commandWait: 2
      browser: "chrome"
    actions:
      - name: "VP_01_HitServer"
        commands: 
          - # Hit server
            hit: "$params.url"
      - name: "VP_02_Login"
        commands:
          - # Enter username
            type:
              selector: "#ctl00_Content_Login1_UserName"
              keys: "$params.username"
          - # Enter password
            type:
              selector: "#ctl00_Content_Login1_Password"
              keys: "$params.password"
          - # Login
            click: "#ctl00_Content_Login1_LoginButton"
            waitAfter: 10
          - # Pin nav menu
            click: "#nav-menu-button"
            condition: "#nav-menu-button"
          - click: "#pin-button"
            condition: "#pin-button[aria-label=Pin]"
          # - if: "#pin-button[aria-label=Pin]"
          #     click: 
          #       selector: "#pin-button"
      - name: "VP_03_EePayrollPayCheckDetail"
        commands:
          - # Click Myself from nav menu
            find: 
              name: "menuTabShadowRoot"
              selector: "shadowRoot(ukg-tab[aria-label=Myself])"
          # Auto collapse nav menu
          - find:
              selector: ".ukg-tab-container"
              from: "$elements.menuTabShadowRoot"
              interaction: click
          - click: "#menu_myself-options-button"
          - click: "//label[contains(text(), 'Collapse All')]"
          # Click 'Pay' nav menu group
          - find:
              name: menuItemGroup
              selector: ukg-nav-item[aria-label='Pay'][level='L1']
          - find: 
              name: "menuItemGroupShadowRoot"
              selector: "shadowRoot($elements.menuItemGroup)"
          - find:
              from: "$elements.menuItemGroupShadowRoot"
              selector: ".nav-item-wrapper"
              interaction: click
            condition: "!$elements.menuItemGroup[aria-expanded]"
          - # Click 'Current Pay Statement' nav menu item
            click: "ukg-nav-item[aria-label='Current Pay Statement'][level='L2']"
      - name: "VP_04_A_EePayrollPayCheckHistory"
        commands:
          click: "ukg-nav-item[aria-label='Pay History'][level='L2']"
      - name: "VP_04_B_EePayrollPayCheckHistory_FilterAll"
        commands:
          - setFrame: "content-frame" 
          - clear: "//input[@class='usDatePickerTextBox' and contains(@id, 'grvPRPayRegister_from')]"
          - clear: "//input[@class='usDatePickerTextBox' and contains(@id, 'grvPRPayRegister_to')]"
          - click: "#grvPRPayRegister_filterButton"
      - name: "VP_05_PayHistoryDetail"
        commands:
          - setWindowSize:
              width: 1920
              height: 1080
          - click: "#ctl00_Content_grvPRPayRegister_ctl02_usclPayDate"
          - setFrame: 0
      - name: "VP_06_EePayrollYTDSummary"
        commands:
          - click: "ukg-nav-item[aria-label='YTD Summary'][level='L2']"
      - name: "VP_07_Logout"
        commands:
          - click: "#unified-nav-header-user-account-menu-button"
          - click: "#ukg-menu-hdr_logout"
  script:
    http:
      assertions:
        - name: "Find 'UKG Pro' on landing page"
          text: "UKG Pro"
      files:
        - name: "Users"
          variants: 
            - "Calendar_Users.dat"
            - "GSDB_Users.dat"
            - "ServiceB_Users.dat"
      parameters: 
        - name: "Username"
          replace: "$params.username"
          file: "Users"
        - name: "Password"
          replace: "$params.password"
          file: "Users"
      correlations:
        - name: "C_XSRF_TOKEN"
          boundary:
            left: "XSRF_TOKEN="
            right: "\n"
          search: "headers"
        - import: "xsrf-token.correlation.yml"
      # logic:
      #   - type: "loop"
      #     loop:
      #       iterations: 5
      #       condition: "$correlations.C_ReportStatus == running"
      #       method: "GET"
      #       url: "*/report/*/status"
      #       action: "Get Report Status"
      #       excludeUrl: "*/report/$correlations.C_ReportStatus/status"